package main

const resourceTemplate = `// Code generated by cmd/generate. DO NOT EDIT.

package generated

import (
	"context"
	"fmt"

	"github.com/StevenBuglione/terraform-provider-comfyui/internal/client"
	"github.com/StevenBuglione/terraform-provider-comfyui/internal/resources"
	"github.com/google/uuid"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
{{- if .NeedsBoolPlanModifier }}
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
{{- end }}
{{- if .NeedsInt64PlanModifier }}
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
{{- end }}
{{- if .NeedsFloat64PlanModifier }}
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/float64planmodifier"
{{- end }}
	"github.com/hashicorp/terraform-plugin-framework/types"
{{- if .NeedsInt64Validator }}
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
{{- end }}
{{- if .NeedsFloat64Validator }}
	"github.com/hashicorp/terraform-plugin-framework-validators/float64validator"
{{- end }}
{{- if .NeedsStringValidator }}
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
{{- end }}
{{- if .NeedsInt64Validator }}
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
{{- else if .NeedsFloat64Validator }}
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
{{- else if .NeedsStringValidator }}
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
{{- end }}
)

var _ resource.Resource = &{{ .StructName }}Resource{}
var _ resource.ResourceWithConfigure = &{{ .StructName }}Resource{}
var _ resource.ResourceWithModifyPlan = &{{ .StructName }}Resource{}

type {{ .StructName }}Resource struct{
	client *client.Client
}

type {{ .StructName }}Model struct {
	ID     types.String ` + "`" + `tfsdk:"id"` + "`" + `
	NodeID types.String ` + "`" + `tfsdk:"node_id"` + "`" + `
{{- range .Fields }}
	{{ .GoName }} {{ .GoType }} ` + "`" + `tfsdk:"{{ .TFName }}"` + "`" + `
{{- end }}
}

func New{{ .StructName }}Resource() resource.Resource {
	return &{{ .StructName }}Resource{}
}

func (r *{{ .StructName }}Resource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T", req.ProviderData),
		)
		return
	}

	r.client = c
}

func (r *{{ .StructName }}Resource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_{{ .TFResourceSuffix }}"
}

func (r *{{ .StructName }}Resource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: {{ .Description | printf "%q" }},
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:    true,
				MarkdownDescription: "Unique identifier for this node instance.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"node_id": schema.StringAttribute{
				Computed:    true,
				MarkdownDescription: "ComfyUI node class type.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
{{- range .Attributes }}
			{{ .Definition }}
{{- end }}
		},
	}
}

func (r *{{ .StructName }}Resource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	if req.Plan.Raw.IsNull() {
		return
	}

	var data {{ .StructName }}Model
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resources.ValidateDynamicInputs(ctx, r.client, {{ .ClassName | printf "%q" }}, data, &resp.Diagnostics)
}

func (r *{{ .StructName }}Resource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data {{ .StructName }}Model
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	data.ID = types.StringValue(uuid.New().String())
	data.NodeID = types.StringValue({{ .ClassName | printf "%q" }})

{{- range .Outputs }}
	data.{{ .GoName }} = types.StringValue(fmt.Sprintf("%s:{{ .SlotIndex }}", data.ID.ValueString()))
{{- end }}

	if err := resources.RegisterNodeStateFromModel(data.ID.ValueString(), data.NodeID.ValueString(), data); err != nil {
		resp.Diagnostics.AddError("Failed to register node state", err.Error())
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *{{ .StructName }}Resource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data {{ .StructName }}Model
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *{{ .StructName }}Resource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data {{ .StructName }}Model
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if err := resources.RegisterNodeStateFromModel(data.ID.ValueString(), data.NodeID.ValueString(), data); err != nil {
		resp.Diagnostics.AddError("Failed to register node state", err.Error())
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *{{ .StructName }}Resource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data {{ .StructName }}Model
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resources.DeleteNodeState(data.ID.ValueString())
}
`

const registryTemplate = `// Code generated by cmd/generate. DO NOT EDIT.

package generated

import "github.com/hashicorp/terraform-plugin-framework/resource"

// ComfyUIVersion is the version of ComfyUI that these resources were generated from.
const ComfyUIVersion = "{{ .ComfyUIVersion }}"

// NodeCount is the total number of generated node resources.
const NodeCount = {{ .NodeCount }}

// ExtractedAt is the timestamp when node specs were extracted.
const ExtractedAt = "{{ .ExtractedAt }}"

// AllResources returns constructor functions for all generated ComfyUI node resources.
func AllResources() []func() resource.Resource {
	return []func() resource.Resource{
{{- range .Constructors }}
		{{ . }},
{{- end }}
	}
}
`

const nodeUIHintsTemplate = `// Code generated by cmd/generate. DO NOT EDIT.

package resources

type generatedWidgetUIHint struct {
	WidgetType     string
	HasComputeSize bool
	ComputedWidth  float64
	ComputedHeight float64
	MinNodeWidth   float64
	MinNodeHeight  float64
}

type generatedNodeUIHint struct {
	MinWidth       float64
	MinHeight      float64
	ComputedWidth  float64
	ComputedHeight float64
	Widgets        map[string]generatedWidgetUIHint
}

const GeneratedNodeUIHintsVersion = "{{ .Version }}"
const GeneratedNodeUIHintsExtractedAt = "{{ .ExtractedAt }}"
const GeneratedNodeUIHintsComfyUICommit = "{{ .ComfyUICommit }}"
const GeneratedNodeUIHintsComfyUIVersion = "{{ .ComfyUIVersion }}"
const GeneratedNodeUIHintsCount = {{ .TotalNodes }}

var generatedNodeUIHints = map[string]generatedNodeUIHint{
{{- range .Nodes }}
	"{{ .NodeType }}": {
		MinWidth: {{ printf "%.6f" .MinWidth }},
		MinHeight: {{ printf "%.6f" .MinHeight }},
		ComputedWidth: {{ printf "%.6f" .ComputedWidth }},
		ComputedHeight: {{ printf "%.6f" .ComputedHeight }},
		Widgets: map[string]generatedWidgetUIHint{
{{- range .Widgets }}
			"{{ .Name }}": {
				WidgetType: "{{ .WidgetType }}",
				HasComputeSize: {{ .HasComputeSize }},
				ComputedWidth: {{ printf "%.6f" .ComputedWidth }},
				ComputedHeight: {{ printf "%.6f" .ComputedHeight }},
				MinNodeWidth: {{ printf "%.6f" .MinNodeWidth }},
				MinNodeHeight: {{ printf "%.6f" .MinNodeHeight }},
			},
{{- end }}
		},
	},
{{- end }}
}
`

const nodeSchemaTemplate = `// Code generated by cmd/generate. DO NOT EDIT.

package nodeschema

type GeneratedNodeSchemaInput struct {
	Name                 string
	Type                 string
	IsLinkType           bool
	ValidationKind       string
	InventoryKind        string
	SupportsStrictPlanValidation bool
	DefaultValue         string
	HasDefaultValue      bool
	MinValue             string
	HasMinValue          bool
	MaxValue             string
	HasMaxValue          bool
	StepValue            string
	HasStepValue         bool
	EnumValues           []string
	Multiline            bool
	DynamicOptions       bool
	DynamicOptionsSource string
	Tooltip              string
	DisplayName          string
}

type GeneratedNodeSchemaHiddenInput struct {
	Name string
	Type string
}

type GeneratedNodeSchemaOutput struct {
	Name      string
	Type      string
	SlotIndex int
	IsList    bool
}

type GeneratedNodeSchema struct {
	NodeType       string
	TerraformType  string
	DisplayName    string
	Description    string
	Category       string
	OutputNode     bool
	Deprecated     bool
	Experimental   bool
	RequiredInputs []GeneratedNodeSchemaInput
	OptionalInputs []GeneratedNodeSchemaInput
	HiddenInputs   []GeneratedNodeSchemaHiddenInput
	Outputs        []GeneratedNodeSchemaOutput
}

const GeneratedNodeSchemaVersion = "{{ .Version }}"
const GeneratedNodeSchemaExtractedAt = "{{ .ExtractedAt }}"
const GeneratedNodeSchemaComfyUIVersion = "{{ .ComfyUIVersion }}"
const GeneratedNodeSchemaCount = {{ .TotalNodes }}

var generatedNodeSchemas = map[string]GeneratedNodeSchema{
{{- range .Nodes }}
	"{{ .NodeType }}": {
		NodeType: "{{ .NodeType }}",
		TerraformType: "{{ .TerraformType }}",
		DisplayName: {{ printf "%q" .DisplayName }},
		Description: {{ printf "%q" .Description }},
		Category: {{ printf "%q" .Category }},
		OutputNode: {{ .OutputNode }},
		Deprecated: {{ .Deprecated }},
		Experimental: {{ .Experimental }},
		RequiredInputs: []GeneratedNodeSchemaInput{
{{- range .RequiredInputs }}
			{
				Name: "{{ .Name }}",
				Type: "{{ .Type }}",
				IsLinkType: {{ .IsLinkType }},
				ValidationKind: {{ printf "%q" .ValidationKind }},
				InventoryKind: {{ printf "%q" .InventoryKind }},
				SupportsStrictPlanValidation: {{ .SupportsStrictPlanValidation }},
				DefaultValue: {{ printf "%q" .DefaultValue }},
				HasDefaultValue: {{ .HasDefaultValue }},
				MinValue: {{ printf "%q" .MinValue }},
				HasMinValue: {{ .HasMinValue }},
				MaxValue: {{ printf "%q" .MaxValue }},
				HasMaxValue: {{ .HasMaxValue }},
				StepValue: {{ printf "%q" .StepValue }},
				HasStepValue: {{ .HasStepValue }},
				EnumValues: []string{
{{- range .EnumValues }}
					{{ printf "%q" . }},
{{- end }}
				},
				Multiline: {{ .Multiline }},
				DynamicOptions: {{ .DynamicOptions }},
				DynamicOptionsSource: {{ printf "%q" .DynamicOptionsSource }},
				Tooltip: {{ printf "%q" .Tooltip }},
				DisplayName: {{ printf "%q" .DisplayName }},
			},
{{- end }}
		},
		OptionalInputs: []GeneratedNodeSchemaInput{
{{- range .OptionalInputs }}
			{
				Name: "{{ .Name }}",
				Type: "{{ .Type }}",
				IsLinkType: {{ .IsLinkType }},
				ValidationKind: {{ printf "%q" .ValidationKind }},
				InventoryKind: {{ printf "%q" .InventoryKind }},
				SupportsStrictPlanValidation: {{ .SupportsStrictPlanValidation }},
				DefaultValue: {{ printf "%q" .DefaultValue }},
				HasDefaultValue: {{ .HasDefaultValue }},
				MinValue: {{ printf "%q" .MinValue }},
				HasMinValue: {{ .HasMinValue }},
				MaxValue: {{ printf "%q" .MaxValue }},
				HasMaxValue: {{ .HasMaxValue }},
				StepValue: {{ printf "%q" .StepValue }},
				HasStepValue: {{ .HasStepValue }},
				EnumValues: []string{
{{- range .EnumValues }}
					{{ printf "%q" . }},
{{- end }}
				},
				Multiline: {{ .Multiline }},
				DynamicOptions: {{ .DynamicOptions }},
				DynamicOptionsSource: {{ printf "%q" .DynamicOptionsSource }},
				Tooltip: {{ printf "%q" .Tooltip }},
				DisplayName: {{ printf "%q" .DisplayName }},
			},
{{- end }}
		},
		HiddenInputs: []GeneratedNodeSchemaHiddenInput{
{{- range .HiddenInputs }}
			{
				Name: "{{ .Name }}",
				Type: "{{ .Type }}",
			},
{{- end }}
		},
		Outputs: []GeneratedNodeSchemaOutput{
{{- range .Outputs }}
			{
				Name: "{{ .Name }}",
				Type: "{{ .Type }}",
				SlotIndex: {{ .SlotIndex }},
				IsList: {{ .IsList }},
			},
{{- end }}
		},
	},
{{- end }}
}

func LookupGeneratedNodeSchema(nodeType string) (GeneratedNodeSchema, bool) {
	schema, ok := generatedNodeSchemas[nodeType]
	return schema, ok
}
`
