package main

const resourceTemplate = `// Code generated by cmd/generate. DO NOT EDIT.

package generated

import (
	"context"
{{- if .HasOutputs }}
	"fmt"
{{- end }}

	"github.com/StevenBuglione/terraform-provider-comfyui/internal/resources"
	"github.com/google/uuid"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
{{- if .NeedsBoolPlanModifier }}
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
{{- end }}
{{- if .NeedsInt64PlanModifier }}
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
{{- end }}
{{- if .NeedsFloat64PlanModifier }}
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/float64planmodifier"
{{- end }}
	"github.com/hashicorp/terraform-plugin-framework/types"
{{- if .NeedsInt64Validator }}
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
{{- end }}
{{- if .NeedsFloat64Validator }}
	"github.com/hashicorp/terraform-plugin-framework-validators/float64validator"
{{- end }}
{{- if .NeedsStringValidator }}
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
{{- end }}
{{- if .NeedsInt64Validator }}
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
{{- else if .NeedsFloat64Validator }}
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
{{- else if .NeedsStringValidator }}
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
{{- end }}
)

var _ resource.Resource = &{{ .StructName }}Resource{}

type {{ .StructName }}Resource struct{}

type {{ .StructName }}Model struct {
	ID     types.String ` + "`" + `tfsdk:"id"` + "`" + `
	NodeID types.String ` + "`" + `tfsdk:"node_id"` + "`" + `
{{- range .Fields }}
	{{ .GoName }} {{ .GoType }} ` + "`" + `tfsdk:"{{ .TFName }}"` + "`" + `
{{- end }}
}

func New{{ .StructName }}Resource() resource.Resource {
	return &{{ .StructName }}Resource{}
}

func (r *{{ .StructName }}Resource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_{{ .TFResourceSuffix }}"
}

func (r *{{ .StructName }}Resource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: {{ .Description | printf "%q" }},
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:    true,
				Description: "Unique identifier for this node instance",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"node_id": schema.StringAttribute{
				Computed:    true,
				Description: "ComfyUI node class type",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
{{- range .Attributes }}
			{{ .Definition }}
{{- end }}
		},
	}
}

func (r *{{ .StructName }}Resource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data {{ .StructName }}Model
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	data.ID = types.StringValue(uuid.New().String())
	data.NodeID = types.StringValue({{ .ClassName | printf "%q" }})

{{- range .Outputs }}
	data.{{ .GoName }} = types.StringValue(fmt.Sprintf("%s:{{ .SlotIndex }}", data.ID.ValueString()))
{{- end }}

	if err := resources.RegisterNodeStateFromModel(data.ID.ValueString(), data.NodeID.ValueString(), data); err != nil {
		resp.Diagnostics.AddError("Failed to register node state", err.Error())
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *{{ .StructName }}Resource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data {{ .StructName }}Model
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *{{ .StructName }}Resource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data {{ .StructName }}Model
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if err := resources.RegisterNodeStateFromModel(data.ID.ValueString(), data.NodeID.ValueString(), data); err != nil {
		resp.Diagnostics.AddError("Failed to register node state", err.Error())
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *{{ .StructName }}Resource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data {{ .StructName }}Model
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resources.DeleteNodeState(data.ID.ValueString())
}
`

const registryTemplate = `// Code generated by cmd/generate. DO NOT EDIT.

package generated

import "github.com/hashicorp/terraform-plugin-framework/resource"

// ComfyUIVersion is the version of ComfyUI that these resources were generated from.
const ComfyUIVersion = "{{ .ComfyUIVersion }}"

// NodeCount is the total number of generated node resources.
const NodeCount = {{ .NodeCount }}

// ExtractedAt is the timestamp when node specs were extracted.
const ExtractedAt = "{{ .ExtractedAt }}"

// AllResources returns constructor functions for all generated ComfyUI node resources.
func AllResources() []func() resource.Resource {
	return []func() resource.Resource{
{{- range .Constructors }}
		{{ . }},
{{- end }}
	}
}
`
